spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${INBOX_CLIENT_ID}
            client-secret: ${INBOX_CLIENT_SECRET}
  data:
    cassandra:
      keyspace-name: main
      username: ${CASSANDRA_USERNAME}
      password: ${CASSANDRA_PASSWORD}
      schema-action: recreate-drop-unused
      request:
        timeout: 20s
      connection:
        connect-timeout: 20s
        init-query-timeout: 20s

astra.db:
  id: ${ASTRA_DB_ID}
  region: ${ASTRA_DB_REGION}
  keyspace: main
  application.token: ${ASTRA_DB_TOKEN}

datastax.astra:
  secure-connect-bundle: secure-connect.zip